// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Polls.Infrastructure;

#nullable disable

namespace Polls.Infrastructure.Migrations
{
    [DbContext(typeof(PollsContext))]
    [Migration("20251031152538_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptionModelPollModel", b =>
                {
                    b.Property<Guid>("OptionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollsId")
                        .HasColumnType("uuid");

                    b.HasKey("OptionsId", "PollsId");

                    b.HasIndex("PollsId");

                    b.ToTable("OptionModelPollModel");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.IterationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PollId")
                        .IsUnique();

                    b.ToTable("IterationModel");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.OptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IterationModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IterationModelId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PersonModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PollModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Polls", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PollStatusModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PollId")
                        .IsUnique();

                    b.ToTable("PollStatusModel");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.VoteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IterationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.HasIndex("OptionId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PollId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.RankedPollModel", b =>
                {
                    b.HasBaseType("Polls.Infrastructure.Models.PollModel");

                    b.ToTable("RankedPolls", (string)null);
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.SingleVotePollModel", b =>
                {
                    b.HasBaseType("Polls.Infrastructure.Models.PollModel");

                    b.ToTable("SingleVotePolls", (string)null);
                });

            modelBuilder.Entity("OptionModelPollModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.OptionModel", null)
                        .WithMany()
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polls.Infrastructure.Models.PollModel", null)
                        .WithMany()
                        .HasForeignKey("PollsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.IterationModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.PollModel", "Poll")
                        .WithOne("Iteration")
                        .HasForeignKey("Polls.Infrastructure.Models.IterationModel", "PollId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.OptionModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.IterationModel", null)
                        .WithMany("Options")
                        .HasForeignKey("IterationModelId");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PollStatusModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.PollModel", "Poll")
                        .WithOne("Status")
                        .HasForeignKey("Polls.Infrastructure.Models.PollStatusModel", "PollId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.VoteModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.IterationModel", "Iteration")
                        .WithMany("Votes")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Polls.Infrastructure.Models.OptionModel", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polls.Infrastructure.Models.PersonModel", "Person")
                        .WithMany("Votes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Polls.Infrastructure.Models.PollModel", "Poll")
                        .WithMany()
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");

                    b.Navigation("Option");

                    b.Navigation("Person");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.RankedPollModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.PollModel", null)
                        .WithOne()
                        .HasForeignKey("Polls.Infrastructure.Models.RankedPollModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.SingleVotePollModel", b =>
                {
                    b.HasOne("Polls.Infrastructure.Models.PollModel", null)
                        .WithOne()
                        .HasForeignKey("Polls.Infrastructure.Models.SingleVotePollModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.IterationModel", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PersonModel", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Polls.Infrastructure.Models.PollModel", b =>
                {
                    b.Navigation("Iteration");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
